host_debian:
  image: tutum/debian:wheezy
  environment:
    - ROOT_PASS=${ROOT_PASS}
    - AUTHORIZED_KEYS=${AUTHORIZED_KEYS}
  volumes:
    - ./release:/usr/build
    - ./logs/debian:/var/log/supervisor/debian
  expose:
    - 22
    - 6420
    - 6402
  ports:
    - "49154:22"
    - "6420:6420"
    - "7420:7420"
  command: /bin/bash -c "apt-get install python -y && /run.sh"

host_alpine:
  build: ./images/alpine
  volumes:
    - ./logs/alpine:/var/log/supervisor/alpine
  environment:
    - AUTHORIZED_KEY=${AUTHORIZED_KEYS}
  expose:
    - 22

ansible:
  image: python:2.7
  environment:
    - ROOT_PASS=${ROOT_PASS}
  links:
    - host_debian
    - host_alpine
  volumes:
    - ./:/etc/ansible
  working_dir: /etc/ansible
  command: /bin/bash -c "./wait-for-it.sh host_debian:22 --timeout=0 && pip install -r requirements.txt && chmod 600 id_rsa && exec ansible-playbook -s main.yml"
