host:
  image: tutum/debian:wheezy
  environment:
    - ROOT_PASS=${ROOT_PASS}
    - AUTHORIZED_KEYS=${AUTHORIZED_KEYS}
  volumes:
    - ./build:/usr/build
  expose:
    - 22
    - 6420
    - 6402
  ports:
    - "49154:22"
    - "6420:6420"
    - "7420:7420"
  command: /bin/bash -c "apt-get install python -y && /run.sh"


ansible:
  image: python:2.7
  environment:
    - ROOT_PASS=${ROOT_PASS}
  links:
    - host
  volumes:
    - ./:/etc/ansible
    - ./ssh:/root/.ssh
  working_dir: /etc/ansible
  command: /bin/bash -c "./wait-for-it.sh host:22 --timeout=0 && pip install ansible && ansible-playbook -s main.yml"